# runs on PR raise from any branch to the develop branch.
# Set '2aae6c35c94fcfb415dbe95f408b9ce91ee846ed' as a github secret and set it as environment variable 'APP TOKEN'
# workflow should include unit-test and build the app.

name: Assignment 3 - Task 2

run-name: PR -> develop, app_token, test & build.

on:
  pull_request:
    branches:
      - develop

jobs:
  using-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Node setup
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "16"
      # - name: Cache node
      #   id: wrkflw2-cc
      #   uses: actions/cache@v3
      #   with:
      #     path: "**/node_modules"
      #     key: ${{ github.actor }}-wrkflw-2-cache-${{ hashFiles('**/packacge-lock.json') }}
      # - if: steps.wrkflw2-cc.outputs.cache-hit != 'true'
      #   run: npm i
      - name: "Install dependency action"
        uses: ./.github/actions/workflow1-action
        with:
          version-of-node: "16.x"
      - name: Unit testing using secrets.
        env:
          APP_TOKEN: ${{ secrets.ASSIGNMENT_3_SEC }}
        run: npm run test
      - name: Build app
        run: npm run build
